import { Poppins } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar";
import Footer from "@/components/Footer";
import { ToastContainer } from "react-toastify";

const poppinsFont = Poppins({
  weight: ['400', '700'],
  subsets: ["latin"],
});


export const metadata = {
  title: "Qurbani Hat",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html
      lang="en"
      className={`${poppinsFont.className} h-full antialiased`}
    >
      <body className="bg-amber-100">
          <Navbar />
          <main>{children} <ToastContainer /></main>
          <Footer />
        </body>
    </html>
  );
}
